/// @file board.h
/// @brief This file specifies the hardware configuration for the project.
///        The various pin/peripheral mappings are tracked here.

#pragma once
#if defined( __cplusplus )
extern "C"
{
#endif // defined(__cplusplus)

// ------------------------------------------------------------------
// Includes
#include "gpio.h"
#include "types.h"

// ------------------------------------------------------------------
// Autogenerated STM CubeMX Definitions
#define EXAMPLE_1_Pin       GPIO_PIN_NUM_2
#define EXAMPLE_1_GPIO_Port GPIO_PORT_E
#define EXAMPLE_2_Pin       GPIO_PIN_NUM_4
#define EXAMPLE_2_GPIO_Port GPIO_PORT_E
#define EXAMPLE_3_Pin       GPIO_PIN_NUM_5
#define EXAMPLE_3_GPIO_Port GPIO_PORT_E
#define EXAMPLE_4_Pin       GPIO_PIN_NUM_6
#define EXAMPLE_4_GPIO_Port GPIO_PORT_E
#define EXAMPLE_5_Pin       GPIO_PIN_NUM_8
#define EXAMPLE_5_GPIO_Port GPIO_PORT_F
#define EXAMPLE_6_Pin       GPIO_PIN_NUM_0
#define EXAMPLE_6_GPIO_Port GPIO_PORT_C
#define EXAMPLE_7_Pin       GPIO_PIN_NUM_1
#define EXAMPLE_7_GPIO_Port GPIO_PORT_C
#define EXAMPLE_8_Pin       GPIO_PIN_NUM_2
#define EXAMPLE_8_GPIO_Port GPIO_PORT_C
#define EXAMPLE_9_Pin       GPIO_PIN_NUM_2
#define EXAMPLE_9_GPIO_Port GPIO_PORT_A

#define USART3_CTS_Pin           GPIO_PIN_NUM_6
#define USART3_CTS_GPIO_Port     GPIO_PORT_A
#define USART3_TX_Pin            GPIO_PIN_NUM_4
#define USART3_TX_GPIO_Port      GPIO_PORT_C
#define USART3_RX_Pin            GPIO_PIN_NUM_5
#define USART3_RX_GPIO_Port      GPIO_PORT_C
#define USART3_RTS_Pin           GPIO_PIN_NUM_1
#define USART3_RTS_GPIO_Port     GPIO_PORT_B

#define USART1_TX_Pin            GPIO_PIN_NUM_9
#define USART1_TX_GPIO_Port      GPIO_PORT_A
#define USART1_RX_Pin            GPIO_PIN_NUM_10
#define USART1_RX_GPIO_Port      GPIO_PORT_A
#define USART1_CTS_Pin           GPIO_PIN_NUM_11
#define USART1_CTS_GPIO_Port     GPIO_PORT_A
#define USART1_RTS_Pin           GPIO_PIN_NUM_12
#define USART1_RTS_GPIO_Port     GPIO_PORT_A

#define SPI3_SCK_Pin             GPIO_PIN_NUM_10
#define SPI3_SCK_GPIO_Port       GPIO_PORT_C
#define SPI3_MISO_Pin            GPIO_PIN_NUM_11
#define SPI3_MISO_GPIO_Port      GPIO_PORT_C
#define SPI3_MOSI_Pin            GPIO_PIN_NUM_12
#define SPI3_MOSI_GPIO_Port      GPIO_PORT_C

#define SPI3_DEVICE_CS_N_Pin            GPIO_PIN_NUM_10
#define SPI3_DEVICE_CS_N_GPIO_Port      GPIO_PORT_G
#define SPI3_DEVICE_GPIO_Pin            GPIO_PIN_NUM_11
#define SPI3_DEVICE_GPIO_GPIO_Port      GPIO_PORT_G
#define SPI3_DEVICE_RESET_N_Pin         GPIO_PIN_NUM_12
#define SPI3_DEVICE_RESET_N_GPIO_Port   GPIO_PORT_G

#define SYSCLK_HZ 120000000U

// Debug logging
#define DEBUG_LOGGING_UART_PERIPHERAL_INDEX UARTBus1

// Macros for a module that uses UART and a timer
#define EXAMPLE_MODULE_1_UART_PERIPHERAL_INDEX UARTBus3
#define EXAMPLE_MODULE_1_TIMER_INDEX           TIMER3

// Macros for a module that uses I2C and timers
// I2C macro will likely be used by a driver for an I2C device
#define EXAMPLE_MODULE_2_I2C_PERIPHERAL_INDEX I2CBus2
#define EXAMPLE_MODULE_2_POLLING_TIMER_INDEX  TIMER4
#define EXAMPLE_MODULE_2_DELAY_TIMER_INDEX    TIMER5

// Macros for a module that uses SPI and a timer
// SPI macro will likely be used by a driver for a SPI device
#define EXAMPLE_MODULE_3_SPI_PERIPHERAL_INDEX SPIBus3
#define EXAMPLE_MODULE_3_TIMEOUT_TIMER_INDEX  TIMER15

#if defined( __cplusplus )
}
#endif // defined(__cplusplus)
